# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_versioning', '0010_version_proxies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangocms_versioning.Version', verbose_name='version')),
            ],
        ),
    ]
